Repository APP-iOS3rd/PJ3T2_Mymory, pull requests merged in 2024-02, with the labels that each got.

#143 Feat/setting view new
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/Components/Button/BackButton.swift
  MyMemory/MyMemory/Source/Extension/Button+Extension.swift
  MyMemory/MyMemory/Source/Extension/Color+Extension.swift
  MyMemory/MyMemory/Source/Extension/Fonts+Extension.swift
  MyMemory/MyMemory/Source/Extension/NavigationBar+Modifier.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoListCell.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageTopView.swift
  MyMemory/MyMemory/View/Detail/Subviews/NavigationBarItems.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/Subviews/FileterListView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/Subviews/addMemoSubView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/View/Setting/Style/ThemeView.swift
  MyMemory/MyMemory/View/Setting/SubViews/SettingMenuCell.swift
Labels: 기능구현, 버그수정, 화면구현

#146 [Feat] Push notification
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyMemory/MyMemory/MyMemoryApp.swift
  MyMemory/MyMemory/Resource/Configure/GoogleService-Info.plist
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Shared/LocationsHandler.swift
  MyMemory/MyMemory/Source/Shared/PushNotification.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/fastlane/report.xml
Labels: 기능구현

#152 [Feat/MenuTabBar]: 메뉴 탭 컴포넌트를 구현했습니다.
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/Components/MenuTabBar.swift
  MyMemory/MyMemory/View/Map/CommunityView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainSectionsView.swift
  MyMemory/MyMemory/View/Map/MemoListView.swift
Labels: 기능구현

#148 MemoCard
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
  MyMemory/MyMemory/Source/Extension/Color+Extension.swift
  MyMemory/MyMemory/Source/Extension/Fonts+Extensions.swift
  MyMemory/MyMemory/Source/Extension/Time+Extensions.swift
  MyMemory/MyMemory/Source/Shared/LocationsHandler.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/ImgDetailView.swift
  MyMemory/MyMemory/View/Map/MemoListView.swift
  MyMemory/MyMemory/View/Map/Subviews/MemoModel.swift
Labels: 기능구현, 화면구현

#157 [Feat]: 메모 스와이프 ScrollView로 변경
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoList.swift
  MyMemory/MyMemory/View/Detail/DetailView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainSectionsView.swift
  MyMemory/MyMemory/View/Map/MemoListView.swift
Labels: 기능구현, 리팩토링

#159 다크모드에서 안보이는 글씨와 SettingMenuCell 코드를 수정했어요
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Configure/MyMemory.entitlements
  MyMemory/MyMemory/Source/Components/Button/BackButton.swift
  MyMemory/MyMemory/Source/Extension/Color+Extension.swift
  MyMemory/MyMemory/Source/Extension/NavigationBar+Modifier.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/OtherUserProfileView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/UserStatusCell.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/CertificationView.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/View/Post/ChangeLocationView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/Subviews/PostViewFooter.swift
  MyMemory/MyMemory/View/Post/Subviews/SelectTagView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/View/Setting/Style/FontView.swift
  MyMemory/MyMemory/View/Setting/Style/ThemeView.swift
  MyMemory/MyMemory/View/Setting/SubViews/SettingMenuCell.swift
  MyMemory/MyMemory/ViewModel/Setting/ThemeViewModel.swift
Labels: 버그수정

#165 [리팩토링] AuthViewModel을 무분별하게 사용하는 부분을 수정했어요
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/API/AuthService.swift
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/Source/Model/User.swift
  MyMemory/MyMemory/View/Authentication/Profile/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/Profile/OtherUserTopView.swift
  MyMemory/MyMemory/View/Authentication/Profile/ProfileView.swift
  MyMemory/MyMemory/View/Authentication/Profile/UserStatusCell.swift
  MyMemory/MyMemory/View/Authentication/ProfileEditView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Post/Subviews/PostViewFooter.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/View/Setting/Style/ThemeView.swift
  MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
  MyMemory/MyMemory/ViewModel/Authentication/ProfileEditViewModel.swift
  MyMemory/MyMemory/ViewModel/Detail/DetailViewModel.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/MypageViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/OtherUserViewModel.swift
Labels: 리팩토링

#166 [Feat]: localize기능을 추가하였습니다.
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Configure/Info.plist
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Source/Components/Button/FilterButton.swift
  MyMemory/MyMemory/View/Authentication/Profile/ProfileView.swift
  MyMemory/MyMemory/View/Post/Subviews/PostViewFooter.swift
Labels: 기능구현

#168 [Feat]메모 카드 수정
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Assets.xcassets/empty.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/empty.imageset/empty.png
  MyMemory/MyMemory/Assets.xcassets/empty.imageset/empty@2x.png
  MyMemory/MyMemory/Assets.xcassets/empty.imageset/empty@3x.png
  MyMemory/MyMemory/Source/API/AuthService.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
  MyMemory/MyMemory/Source/Extension/Button+Extension.swift
  MyMemory/MyMemory/View/Authentication/Profile/MyPageEmptyView.swift
  MyMemory/MyMemory/View/Authentication/Profile/ProfileView.swift
  MyMemory/MyMemory/View/Authentication/ProfileEditView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainSectionsView.swift
  MyMemory/MyMemory/View/Post/ChangeLocationView.swift
  MyMemory/MyMemory/ViewModel/Authentication/ProfileEditViewModel.swift
  MyMemory/MyMemory/ViewModel/Map/MainMapViewModel.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
  MyMemory/fastlane/report.xml
Labels: 기능구현, 리팩토링

#169 [Feat]: 각종 뷰 개선(로그인, 작성 뷰)
  MyMemory/MyMemory/Assets.xcassets/GoogleLogo.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/GoogleLogo.imageset/google_logo.svg
  MyMemory/MyMemory/Source/Components/Button/BackButton.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/Source/Extension/Button+Extension.swift
  MyMemory/MyMemory/Source/Extension/Color+Extension.swift
  MyMemory/MyMemory/Source/Extension/NavigationBar+Modifier.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/View/Authentication/Profile/UserStatusCell.swift
  MyMemory/MyMemory/View/Authentication/ProfileEditView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/Subviews/addMemoSubView.swift
Labels: 리팩토링, 화면구현

#187 Refactoring/MyPage : MyPage, OtherUser Profile 분리 작업 🙆🏻
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/MyMemoryDebug.entitlements
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Resource/Configure/MyMemory.entitlements
  MyMemory/MyMemory/View/Authentication/MyPage/MapImageMarkerView.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MyPageView.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/MyPage/ProfileEditView.swift
  MyMemory/MyMemory/View/Authentication/MyPageEmptyView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/MypageViewModel.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserTopView.swift
  MyMemory/MyMemory/View/Authentication/Profile/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoList.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoListCell.swift
  MyMemory/MyMemory/View/Authentication/UserStatusCell.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/ViewModel/Profile/MyPage/MypageViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/OtherUser/OtherUserViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/ProfileViewModelProtocol.swift
Labels: 기능구현, 버그수정, 리팩토링

#183 [Fix] 팔로우 바인딩
  MyMemory/.gitignore
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Assets.xcassets/GoogleLogo.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/GoogleLogo.imageset/google_logo.svg
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Source/API/AuthService.swift
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Components/Button/BackButton.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/Source/Components/MenuTabBar.swift
  MyMemory/MyMemory/Source/Extension/Button+Extension.swift
  MyMemory/MyMemory/Source/Extension/NavigationBar+Modifier.swift
  MyMemory/MyMemory/Source/Model/User.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/View/Authentication/MapImageMarkerView.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/MyProfile/MyPageView.swift
  MyMemory/MyMemory/View/Authentication/MyProfile/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/MyProfile/ProfileEditView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserTopView.swift
  MyMemory/MyMemory/View/Authentication/Profile/MypageViewModel.swift
  MyMemory/MyMemory/View/Authentication/Profile/OtherUserTopView.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoList.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoListCell.swift
  MyMemory/MyMemory/View/Authentication/RegisterView.swift
  MyMemory/MyMemory/View/Authentication/UserStatusCell.swift
  MyMemory/MyMemory/View/Detail/DetailView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/View/Detail/Subviews/NavigationBarItems.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Map/CommunityView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainSectionsView.swift
  MyMemory/MyMemory/View/Map/MemoListView.swift
  MyMemory/MyMemory/View/Post/ChangeLocationView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/Subviews/PostViewFooter.swift
  MyMemory/MyMemory/View/Post/Subviews/SelectTagView.swift
  MyMemory/MyMemory/View/Post/Subviews/addMemoSubView.swift
  MyMemory/MyMemory/View/Setting/Style/ThemeView.swift
  MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
  MyMemory/MyMemory/ViewModel/Authentication/RegisterViewModel.swift
  MyMemory/MyMemory/ViewModel/Detail/DetailViewModel.swift
  MyMemory/MyMemory/ViewModel/Map/MainMapViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/MemoListViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/MyProfile/MypageViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/OtherUser/OtherUserViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/OtherUserViewModel.swift
  MyMemory/fastlane/report.xml
Labels: 기능구현, 버그수정

#188 [Feat] 내 메모 분기처리
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoList.swift
  MyMemory/MyMemory/View/Detail/DetailView.swift
Labels: 기능구현

#189 [Feat] 신고하기 기능을 구현했습니다.
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/API/Constants.swift
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Components/SelectBox.swift
  MyMemory/MyMemory/Source/Model/Authentication/Report.swift
  MyMemory/MyMemory/View/Authentication/ReportView.swift
  MyMemory/MyMemory/View/Detail/Subviews/NavigationBarItems.swift
  MyMemory/MyMemory/ViewModel/Detail/ReportViewModel.swift
Labels: 기능구현

#191 [Fix] PostView
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Resource/Configure/MyMemory.entitlements
  MyMemory/MyMemory/Source/API/AuthService.swift
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Shared/LocationsHandler.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/MyProfile/MyPageView.swift
  MyMemory/MyMemory/View/Authentication/MyProfile/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/MyProfile/ProfileEditView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/MypageViewModel.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserTopView.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoList.swift
  MyMemory/MyMemory/View/Detail/DetailView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/View/Detail/Subviews/NavigationBarItems.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/Subviews/SelectPhotos.swift
  MyMemory/MyMemory/View/Post/Subviews/SelectTagView.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/OtherUser/OtherUserViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/ProfileViewModelProtocol.swift
Labels: 버그수정, 리팩토링

#193 [Refactoring]: 현재 위치에 따라 메모 숨기기
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/ViewModel/Detail/DetailViewModel.swift
Labels: 리팩토링

#194 [Fix] Profile Edit뷰 및 기타 수정 작업
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Assets.xcassets/ScrollTop.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/ScrollTop.imageset/ScrollTop.png
  MyMemory/MyMemory/Assets.xcassets/ScrollTop.imageset/ScrollTop@2x.png
  MyMemory/MyMemory/Assets.xcassets/ScrollTop.imageset/ScrollTop@3x.png
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Source/API/AuthService.swift
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/Source/Components/MenuTabBar.swift
  MyMemory/MyMemory/Source/Model/User.swift
  MyMemory/MyMemory/Source/Shared/GetAddress.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MyPageView.swift
  MyMemory/MyMemory/View/Authentication/MyPage/ProfileEditView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoList.swift
  MyMemory/MyMemory/View/Authentication/ReportView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/ImgDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/View/Map/CommunityView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainSectionsView.swift
  MyMemory/MyMemory/View/Post/Subviews/addMemoSubView.swift
  MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
  MyMemory/MyMemory/ViewModel/Authentication/ProfileEditViewModel.swift
  MyMemory/MyMemory/ViewModel/Detail/CertificationViewModel.swift
  MyMemory/MyMemory/ViewModel/Map/MainMapViewModel.swift
  MyMemory/fastlane/report.xml
Labels: 버그수정, 리팩토링

#198 [Refactoring]: 프로필 수정하기 기능을 수정했습니다.
  MyMemory/MyMemory/Source/Extension/Fonts+Extensions.swift
  MyMemory/MyMemory/Source/Extension/String+Extension.swift
  MyMemory/MyMemory/Source/Model/User.swift
  MyMemory/MyMemory/View/Authentication/MyPage/ProfileEditView.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoList.swift
  MyMemory/MyMemory/ViewModel/Authentication/ProfileEditViewModel.swift
Labels: 기능구현, 리팩토링

#200 Adapt like
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/View/Authentication/MyPage/ProfileEditView.swift
  MyMemory/MyMemory/View/Detail/Subviews/NavigationBarItems.swift
  MyMemory/fastlane/report.xml
Labels: 기능구현, 버그수정

#209 [fix]: 프로필 변경 시 발생하는 에러들을 수정했습니다.
  MyMemory/MyMemory/View/Authentication/MyPage/ProfileEditView.swift
  MyMemory/MyMemory/ViewModel/Authentication/ProfileEditViewModel.swift
Labels: 버그수정

#213 [Feat] 온보딩 뷰
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Assets.xcassets/onboarding0.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/onboarding0.imageset/onboarding0.png
  MyMemory/MyMemory/Assets.xcassets/onboarding1-1.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/onboarding1-1.imageset/onboarding1-1.png
  MyMemory/MyMemory/Assets.xcassets/onboarding2.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/onboarding2.imageset/onboarding2.png
  MyMemory/MyMemory/Assets.xcassets/onboarding3.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/onboarding3.imageset/onboarding3.png
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Onboarding/Onboarding.swift
  MyMemory/MyMemory/View/Onboarding/OnboardingView.swift
  MyMemory/MyMemory/View/Onboarding/Subviews/IndexView.swift
  MyMemory/MyMemory/ViewModel/Onboarding/OnboardingViewModel.swift
Labels: 기능구현

#215 [Fix] 프로필 메모리스트에서 작성자의 이름이 제대로 표시되게 수정
  MyMemory/MyMemory/View/Authentication/ProfileMemoList.swift
Labels: 버그수정

#220 Feat/theme font
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/Shared/ThemeManager.swift
  MyMemory/MyMemory/View/Map/CommunityView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Setting/Style/ThemeView.swift
Labels: 기능구현, 리팩토링

#223 [Bug]: 작성하기 후 마이페이지 접근 시 무한로딩이 발생하는 경우를 해결하였습니다.
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
Labels: 버그수정

#222 [Fix]: 탭바 투명화 수정
  MyMemory/MyMemory/View/Main/MainTabView.swift
Labels: 버그수정

#227 [Refactoring]: 기존의 회원탈퇴 로직에서 회원의 프로필 사진을 Storage에서 삭제하는 코드를 추가하였습니다.
  MyMemory/MyMemory/Source/API/AuthService.swift
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/View/Setting/SettingMenu/WithdrawalView.swift
  MyMemory/MyMemory/ViewModel/Authentication/ProfileEditViewModel.swift
Labels: 기능구현, 리팩토링

#229 [Refactoring]: 설정 뷰와 회원탈퇴 뷰의 디자인을 최신화했습니다.
  MyMemory/MyMemory/View/Authentication/RegisterView.swift
  MyMemory/MyMemory/View/Setting/SettingMenu/WithdrawalView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/View/Setting/SubViews/SettingMenuCell.swift
  MyMemory/MyMemory/View/Setting/SubViews/TermsView.swift
Labels: 리팩토링

#228 [Feat] PostView에서 메모지선택하게 하기
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Resource/Configure/MyMemory.entitlements
  MyMemory/MyMemory/Source/Extension/Color+Extension.swift
  MyMemory/MyMemory/Source/Shared/ThemeManager.swift
  MyMemory/MyMemory/View/Detail/Subviews/NavigationBarItems.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Setting/Style/ThemeView.swift
  MyMemory/MyMemory/ViewModel/Setting/ThemeViewModel.swift
Labels: 기능구현, 화면구현

#232 [Refactoring]: 설정 뷰에서 모든 메뉴들을 연결했습니다.
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/View/Authentication/MyPage/ProfileEditView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/View/Setting/SubViews/SettingMenuCell.swift
  MyMemory/MyMemory/ViewModel/Setting/SettingViewModel.swift
  MyMemory/Settings.bundle/Root.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  MyMemory/Settings.bundle/com.mono0926.LicensePlist.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/Alamofire.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/AppAuth-iOS.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/FLAnimatedImage.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/GTMAppAuth.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/GoogleAppMeasurement.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/GoogleDataTransport.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/GoogleSignIn-iOS.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/GoogleUtilities.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/Kingfisher.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/abseil-cpp-binary.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/app-check.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/firebase-ios-sdk.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/grpc-binary.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/gtm-session-fetcher.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/interop-ios-for-google-sdks.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/kakao-ios-sdk.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/leveldb.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/nanopb.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/promises.plist
  MyMemory/Settings.bundle/com.mono0926.LicensePlist/swift-protobuf.plist
  MyMemory/Settings.bundle/en.lproj/Root.strings
Labels: 리팩토링

#231 [Refactoring] 커뮤니티에서 거리 상관없이 메모 확인
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Map/CommunityView.swift
Labels: 리팩토링

#239 [Refactoring]: 로그인이 아닌 상태에서 마이페이지 접근 시 화면을 수정했습니다.
  MyMemory/MyMemory/View/Authentication/MyPage/MyPageView.swift
Labels: 리팩토링

#242 Refactoring/feedback mainview
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/API/Constants.swift
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/Source/Components/TopBarAddress.swift
  MyMemory/MyMemory/Source/Shared/GetAddress.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainSectionsView.swift
  MyMemory/MyMemory/View/Map/Subviews/FileterListView.swift
  MyMemory/MyMemory/View/Map/Subviews/MapView.swift
  MyMemory/MyMemory/View/Post/ChangeLocationView.swift
  MyMemory/MyMemory/ViewModel/Map/MainMapViewModel.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
Labels: 리팩토링

#245 [Fix] 로그인 뷰 오류 수정
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/Extension/UIApplication+Extesions.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
Labels: 버그수정

#247 :art: 권한없을 때 예외처리 다 했음
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Source/Components/Alert/AlertButtonView.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoList.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/CertificationView.swift
  MyMemory/MyMemory/View/Detail/Subviews/NavigationBarItems.swift
  MyMemory/MyMemory/View/Map/CommunityView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainSectionsView.swift
  MyMemory/MyMemory/View/Onboarding/OnboardingView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/ViewModel/Detail/CertificationViewModel.swift
  MyMemory/fastlane/report.xml
Labels: 리팩토링

#255 [Feat] postView에 카메라 기능을 추가했습니다!
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyMemory/MyMemory/MyMemoryDebug.entitlements
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Resource/Configure/MyMemory.entitlements
  MyMemory/MyMemory/Source/Shared/ImagePicker.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/Subviews/CustomPhotosPicker.swift
  MyMemory/MyMemory/View/Post/Subviews/SelectPhotos.swift
  MyMemory/MyMemory/ViewModel/Post/PhotosViewModel.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
  MyMemory/fastlane/report.xml
Labels: 기능구현, 리팩토링

#256 [Refactoring]: OtherProfileView의 디자인 및 메서드들을 수정했습니다.
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserEmptyView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserTopView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/DetailViewMemoMoveButton.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/ViewModel/Detail/DetailViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/OtherUser/OtherUserViewModel.swift
Labels: 리팩토링

#258 [Refactor]: 디테일뷰 및 UI 수정
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Assets.xcassets/AccentColor.colorset/Contents.json
  MyMemory/MyMemory/Launch Screen.storyboard
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
  MyMemory/MyMemory/View/Authentication/GoogleSocialRegisterView.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MyPageView.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserTopView.swift
  MyMemory/MyMemory/View/Authentication/SocialRegisterView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/DetailBottomAddressView.swift
  MyMemory/MyMemory/View/Detail/Subviews/DetailViewListCell.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/View/Detail/Subviews/NavigationBarItems.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Main/MainView.swift
  MyMemory/MyMemory/View/Onboarding/OnboardingView.swift
Labels: 리팩토링, 화면구현

#259 [Fix]: OtherUserProfileView의 어색한 부분을 수정했습니다
  MyMemory/MyMemory/View/Authentication/FollowFollowingList.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
  MyMemory/MyMemory/View/Authentication/UserStatusCell.swift
Labels: 버그수정, 화면구현

#260 :fire: Tag기능 고도화
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Source/API/AuthService.swift
  MyMemory/MyMemory/Source/API/Constants.swift
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/API/TagService.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/Source/Model/User.swift
  MyMemory/MyMemory/Source/Shared/LocationsHandler.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MapImageMarkerView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserTopView.swift
  MyMemory/MyMemory/View/Authentication/ProfileMemoList.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/DetailViewListCell.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/View/Map/CommunityView.swift
  MyMemory/MyMemory/View/Map/MainSectionsView.swift
  MyMemory/MyMemory/View/Map/Subviews/FileterListView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/Subviews/SelectTagView.swift
  MyMemory/MyMemory/View/Post/Subviews/addMemoSubView.swift
  MyMemory/MyMemory/ViewModel/Detail/MoveUserProfileViewModel.swift
  MyMemory/MyMemory/ViewModel/Map/MainMapViewModel.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
  MyMemory/MyMemory/ViewModel/Profile/OtherUser/OtherUserViewModel.swift
Labels: 기능구현

#262 [Feat] 해당장소모아보기 Placeview 를 작업했어요.
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyMemory/MyMemory/Assets.xcassets/AccentColor.colorset/Contents.json
  MyMemory/MyMemory/MyMemoryDebug.entitlements
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Resource/Configure/MyMemory.entitlements
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCard.swift
  MyMemory/MyMemory/Source/Extension/Button+Extension.swift
  MyMemory/MyMemory/Source/Extension/NavigationBar+Modifier.swift
  MyMemory/MyMemory/Source/Model/Memo.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/DetailViewListCell.swift
  MyMemory/MyMemory/View/Map/CommunityView.swift
  MyMemory/MyMemory/View/Map/PlaceView.swift
  MyMemory/MyMemory/View/Post/Subviews/SelectTagView.swift
  MyMemory/MyMemory/ViewModel/Map/PlaceViewModel.swift
Labels: 기능구현, 화면구현

#269 [Refactoring] 사용자 UX를 개선했어요.
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Assets.xcassets/kakao.imageset/Contents.json
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Source/Components/MenuTabBar.swift
  MyMemory/MyMemory/Source/Shared/ThemeManager.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MyPageView.swift
  MyMemory/MyMemory/View/Authentication/MyPage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/OtherUser/OtherUserProfileView.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Map/CommunityTabView.swift
  MyMemory/MyMemory/View/Map/CommunityView.swift
  MyMemory/MyMemory/View/Map/ListView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainSectionsView.swift
  MyMemory/MyMemory/View/Map/PlaceView.swift
  MyMemory/MyMemory/View/Setting/SettingTabView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/View/Setting/Style/ThemeView.swift
Labels: 리팩토링, 화면구현

#272 [Feat] 각 메모의 Font 스타일 적용하기 CRUD
  MyMemory/MyMemory/Resource/Configure/Localizable.xcstrings
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Extension/Fonts+Extensions.swift
  MyMemory/MyMemory/Source/Model/Memo.swift
  MyMemory/MyMemory/Source/Model/PostMemoModel.swift
  MyMemory/MyMemory/Source/Shared/FontManager.swift
  MyMemory/MyMemory/Source/Shared/ThemeManager.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/DetailViewListCell.swift
  MyMemory/MyMemory/View/Detail/Subviews/MoveUserProfileButton.swift
  MyMemory/MyMemory/View/Detail/Subviews/NavigationBarItems.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/Subviews/SelectPhotos.swift
  MyMemory/MyMemory/View/Post/Subviews/addMemoSubView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/View/Setting/Style/FontView.swift
  MyMemory/MyMemory/View/Setting/SubViews/SettingMenuCell.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
Labels: 기능구현, 화면구현
