Repository APP-iOS3rd/PJ3T2_Mymory, pull requests merged in 2024-01, with the labels that each got.

#13 Featmap view
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory.xcodeproj/xcshareddata/xcschemes/MyMemory.xcscheme
  MyMemory/MyMemory/Info.plist
  MyMemory/MyMemory/MyMemoryApp.swift
  MyMemory/MyMemory/Resource/CornerShape.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainMapViewModel.swift
  MyMemory/MyMemory/View/Map/MapView.swift
  MyMemory/MyMemory/View/Map/MapViewRepresentable.swift
  MyMemory/MyMemory/View/Map/MemoModel.swift
  MyMemory/MyMemoryTests/MapViewModelTest.swift
Labels: 화면구현

#14 Setting/fastlane CI/CD 환경 설정을 해 보았습니다!
  .gitignore
  MyMemory/AuthKey_Z977X9A9MU.p8
  MyMemory/Gemfile
  MyMemory/Gemfile.lock
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/AppIcon.appiconset/tempIcon1024.png
  MyMemory/MyMemory/Info.plist
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainMapViewModel.swift
  MyMemory/MyMemory/View/Map/MapViewRepresentable.swift
  MyMemory/fastlane/.env.default
  MyMemory/fastlane/Appfile
  MyMemory/fastlane/Fastfile
  MyMemory/fastlane/Matchfile
  MyMemory/fastlane/README.md
  MyMemory/fastlane/Z977X9A9MU.json
  MyMemory/fastlane/report.xml
Labels: 환경설정

#31 Refactoring/maps 카카오맵 연동 했습니다.
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyMemory/MyMemory/Info.plist
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Map/KakaoMap.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MapViewRepresentable.swift
Labels: 리팩토링

#35 Refactoring/maps 지도뷰 중간 Merge
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Info.plist
  MyMemory/MyMemory/Model/AddressModel.swift
  MyMemory/MyMemory/Shared/GetAddress.swift
  MyMemory/MyMemory/View/Map/KakaoMap.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainMapViewModel.swift
  MyMemory/MyMemory/View/Map/Subviews/ClusterSelectionView.swift
Labels: 기능구현, 리팩토링

#65 :recycle: Quad tree 사용하는 Clustering으로 변경
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/AppIcon.appiconset/tempIcon1024.png
  MyMemory/MyMemory/Assets.xcassets/AppIcon.appiconset/임시아이콘.png
  MyMemory/MyMemory/Assets.xcassets/logo.imageset/Image.png
  MyMemory/MyMemory/Assets.xcassets/maker_mine_selected.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/maker_mine_selected.imageset/maker_mine_selected.png
  MyMemory/MyMemory/Assets.xcassets/maker_mine_selected.imageset/maker_mine_selected@2x.png
  MyMemory/MyMemory/Assets.xcassets/maker_mine_selected.imageset/maker_mine_selected@3x.png
  MyMemory/MyMemory/Assets.xcassets/marker_default.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/marker_default.imageset/marker_default.png
  MyMemory/MyMemory/Assets.xcassets/marker_default.imageset/marker_default@2x.png
  MyMemory/MyMemory/Assets.xcassets/marker_default.imageset/marker_default@3x.png
  MyMemory/MyMemory/Assets.xcassets/marker_mine.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/marker_mine.imageset/marker_mine.png
  MyMemory/MyMemory/Assets.xcassets/marker_mine.imageset/marker_mine@2x.png
  MyMemory/MyMemory/Assets.xcassets/marker_mine.imageset/marker_mine@3x.png
  MyMemory/MyMemory/Assets.xcassets/marker_selected.imageset/Contents.json
  MyMemory/MyMemory/Assets.xcassets/marker_selected.imageset/marker_selected.png
  MyMemory/MyMemory/Assets.xcassets/marker_selected.imageset/marker_selected@2x.png
  MyMemory/MyMemory/Assets.xcassets/marker_selected.imageset/marker_selected@3x.png
  MyMemory/MyMemory/Cluster/ClusterBox.swift
  MyMemory/MyMemory/Cluster/Clustering.swift
  MyMemory/MyMemory/Cluster/QuadTree.swift
  MyMemory/MyMemory/Info.plist
  MyMemory/MyMemory/Resource/Extension/Button+Extension.swift
  MyMemory/MyMemory/Resource/Extension/Color+Extension.swift
  MyMemory/MyMemory/Resource/Extension/String+Extension.swift
  MyMemory/MyMemory/Resource/Extension/view+Extension.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageViewModel.swift
  MyMemory/MyMemory/View/Components/Button/FilterButton.swift
  MyMemory/MyMemory/View/Components/FlexibleView.swift
  MyMemory/MyMemory/View/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Components/Memo/MemoListView.swift
  MyMemory/MyMemory/View/Map/KakaoMap.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainMapViewModel.swift
  MyMemory/MyMemory/View/Map/MemoModel.swift
  MyMemory/MyMemory/View/Map/Subviews/FileterListView.swift
  MyMemory/fastlane/report.xml
Labels: 버그수정, 리팩토링, 화면구현

#68 Feat/uiadvance2
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Extension/NavigationBar+Modifier.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoList.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/View/Authentication/RegisterView.swift
  MyMemory/MyMemory/View/Components/Button/CloseButton.swift
  MyMemory/MyMemory/View/Components/LoadingView.swift
  MyMemory/MyMemory/View/Components/TopBarAddress.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/MiniMap.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/ProgressBarView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Search/SearchView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/fastlane/report.xml
Labels: 화면구현

#69 Feat/mypage 파이어베이스 연동
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/View/Authentication/Mypage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageViewModel.swift
  MyMemory/MyMemory/View/Authentication/ProfileEditView.swift
  MyMemory/MyMemory/View/Authentication/ProfileEditViewModel.swift
  MyMemory/MyMemory/View/Setting/SettingMenu/WithdrawalView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/View/Setting/SettingViewModel.swift
Labels: 기능구현

#70 Refactoring/firebase auth1
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/API/ImageUploader.swift
  MyMemory/MyMemory/Model/User.swift
  MyMemory/MyMemory/Resource/Constants.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/View/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
Labels: 기능구현, 버그수정, 리팩토링

#72 Refactoring/minor UI fix
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Cluster/Clustering.swift
  MyMemory/MyMemory/MyMemory.entitlements
  MyMemory/MyMemory/Shared/LoadingManager.swift
  MyMemory/MyMemory/Shared/LocationsHandler.swift
  MyMemory/MyMemory/View/Components/LoadingView.swift
  MyMemory/MyMemory/View/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Components/Memo/MemoListView.swift
  MyMemory/MyMemory/View/Components/TopBarAddress.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/GIFView.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Main/MainView.swift
  MyMemory/MyMemory/View/Main/MemoMapView.swift
  MyMemory/MyMemory/View/Map/KakaoMap.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainMapViewModel.swift
  MyMemory/MyMemory/View/Map/Subviews/FileterListView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
Labels: 리팩토링, 화면구현

#79 Feat/certification view
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Extension/CLLocation+Extension.swift
  MyMemory/MyMemory/View/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Detail/CertificationView.swift
  MyMemory/MyMemory/View/Detail/CertificationViewModel.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/CertificationMap.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/MiniMap.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/ProgressBarView.swift
Labels: 기능구현

#78 Refactoring/detail view 디테일뷰 최신화
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Resource/Extension/Button+Extension.swift
  MyMemory/MyMemory/Resource/Extension/Color+Extension.swift
  MyMemory/MyMemory/Resource/Extension/Fonts+Extension.swift
  MyMemory/MyMemory/Shared/KakaoMapSimple.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Post/ChangeLocationView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/PostViewModel.swift
  MyMemory/fastlane/report.xml
Labels: 리팩토링

#85 Refactoring/map view ref
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/API/MemoService.swift
  MyMemory/MyMemory/View/Authentication/ReportView.swift
  MyMemory/MyMemory/View/Components/Memo/MemoListView.swift
  MyMemory/MyMemory/View/Components/ReportMemoView.swift
  MyMemory/MyMemory/View/Components/Textarea.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/NavigationBarItems.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/MainMapViewModel.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
  MyMemory/fastlane/report.xml
Labels: 리팩토링

#91 Feat/view connect
  MyMemory/MyMemory/View/Detail/DetailViewComponent/NavigationBarItems.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
Labels: 버그수정

#95 [Refactoring]: 기존 코드 정리 및 자잘한 오류 수정
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/View/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Detail/CertificationView.swift
  MyMemory/MyMemory/View/Detail/CertificationViewModel.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/CertificationMap.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/MiniMap.swift
  MyMemory/MyMemory/View/Detail/DetailViewComponent/ProgressBarView.swift
Labels: 버그수정, 리팩토링

#101 Fix: AuthViewModel 내 FetchUser() 무한 호출 이슈
  MyMemory/MyMemory/View/Authentication/Mypage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageViewModel.swift
  MyMemory/MyMemory/View/Main/MainTabView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
Labels: 버그수정

#104 [Refactoring]: 마이페이지 메모리스트에서 현재 사용자의 위치와의 거리를 나타내도록 수정하였습니다.
  MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoList.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoListCell.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageViewModel.swift
Labels: 리팩토링

#109 Refactoring/fix foldering
  MyMemory/MyMemory/Source/Shared/KakaoMapSimple.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/View/Detail/Subviews/CertificationMap.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/Subviews/KakaoMap.swift
  MyMemory/MyMemory/View/Onboarding/OnboardingView.swift
  MyMemory/MyMemory/ViewModel/Map/MainMapViewModel.swift
  MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
Labels: 리팩토링

#112 Refactoring/protocol
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/API/FirebaseProtocol.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/View/Map/Subviews/KakaoMap.swift
Labels: 리팩토링

#118 [Refactoring]: 현재 위치와 메모간의 거리를 불러오는 로직을 수정하였습니다. (피드백 반영)
  MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoListCell.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift
Labels: 리팩토링

#120 Migration/mapkit
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Cluster/ClusterBox.swift
  MyMemory/MyMemory/Source/Cluster/Clustering.swift
  MyMemory/MyMemory/Source/Cluster/QuadTree.swift
  MyMemory/MyMemory/Source/ViewModelUsingMap.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Map/Subviews/KakaoMap.swift
  MyMemory/MyMemory/View/Map/Subviews/MapView.swift
  MyMemory/MyMemory/ViewModel/Authentication/ProfileEditViewModel.swift
  MyMemory/MyMemory/ViewModel/Map/MainMapViewModel.swift
  MyMemory/MyMemory/ViewModel/Map/MapViewModel.swift
Labels: 리팩토링

#121 Fix to mapkit
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/Source/Cluster/Clustering.swift
  MyMemory/MyMemory/Source/Cluster/QuadTree.swift
  MyMemory/MyMemory/Source/Components/Memo/MemoCell.swift
  MyMemory/MyMemory/View/Map/Subviews/MapView.swift
  MyMemory/MyMemory/View/Post/ChangeLocationView.swift
  MyMemory/MyMemory/View/Post/Subviews/PostViewFooter.swift
  MyMemory/MyMemory/ViewModel/Authentication/ProfileEditViewModel.swift
  MyMemory/MyMemory/ViewModel/Map/MainMapViewModel.swift
  MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
Labels: 리팩토링, 화면구현

#123 :sparkles: 카카오맵 삭제
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/Cluster/ClusterBox.swift
  MyMemory/MyMemory/Source/Cluster/Clustering.swift
  MyMemory/MyMemory/Source/Model/PostMemoModel.swift
  MyMemory/MyMemory/Source/Shared/KakaoMapSimple.swift
  MyMemory/MyMemory/Source/ViewModelUsingMap.swift
  MyMemory/MyMemory/View/Detail/Subviews/CertificationMap.swift
  MyMemory/MyMemory/View/Detail/Subviews/CertificationView.swift
  MyMemory/MyMemory/View/Map/Subviews/KakaoMap.swift
  MyMemory/MyMemory/View/Map/Subviews/MapView.swift
  MyMemory/MyMemory/ViewModel/Detail/CertificationViewModel.swift
  MyMemory/MyMemory/ViewModel/Map/MainMapViewModel.swift
  MyMemory/MyMemory/ViewModel/Map/MapViewModel.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
  MyMemory/fastlane/report.xml
Labels: 리팩토링, 화면구현

#127 뷰 조금 손봤어요
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyMemory/MyMemory/MyMemoryApp.swift
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoList.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Detail/Subviews/ImgDetailView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
  MyMemory/MyMemory/View/Post/Subviews/PostViewFooter.swift
  MyMemory/MyMemory/View/Post/Subviews/SelectTagView.swift
  MyMemory/MyMemory/View/Setting/SettingView.swift
  MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
  MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift
  MyMemory/MyMemory/ViewModel/Post/PostViewModel.swift
Labels: 리팩토링

#128 다크모드 적용을 위한 Color+Extension을 작업했어요.
  MyMemory/MyMemory.xcodeproj/project.pbxproj
  MyMemory/MyMemory/Source/Components/Button/BackButton.swift
  MyMemory/MyMemory/Source/Components/Button/CloseButton.swift
  MyMemory/MyMemory/Source/Components/Button/CurrentSpotButton.swift
  MyMemory/MyMemory/Source/Components/TopBarAddress.swift
  MyMemory/MyMemory/Source/Extension/Button+Extension.swift
  MyMemory/MyMemory/Source/Extension/Color+Extension.swift
  MyMemory/MyMemory/Source/Extension/Fonts+Extension.swift
  MyMemory/MyMemory/Source/Extension/NavigationBar+Modifier.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoListCell.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageTopView.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/View/Detail/MemoDetailView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
Labels: 리팩토링, 화면구현

#131 [Feat/pagenation] : 페이지네이션(무한스크롤)을 구현했습니다.
  MyMemory/MyMemory/Source/API/MemoService.swift
  MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift
Labels: 기능구현

#132 [Refactoring]: 마이페이지 페이지네이션 적용
  MyMemory/MyMemory/View/Authentication/Mypage/MypageMemoList.swift
  MyMemory/MyMemory/View/Authentication/Mypage/MypageView.swift
  MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift
Labels: 리팩토링

#139 [Feat]: 위치정보동의 안내 구현 및 CustomAlert 수정
  MyMemory/MyMemory.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyMemory/MyMemory/Source/Components/Alert/AlertButtonView.swift
  MyMemory/MyMemory/Source/Components/Alert/AlertView.swift
  MyMemory/MyMemory/View/Map/MainMapView.swift
  MyMemory/MyMemory/View/Post/PostView.swift
Labels: 기능구현

#142 [Refactoring/loginview]: Email 로그인 실패 시 그냥 dismiss되는 부분 수정 및 추가 작업
  MyMemory/MyMemory/MyMemoryApp.swift
  MyMemory/MyMemory/View/Authentication/LoginView.swift
  MyMemory/MyMemory/ViewModel/Authentication/AuthViewModel.swift
  MyMemory/MyMemory/ViewModel/Mypage/MypageViewModel.swift
Labels: 리팩토링
